flowchart LR
    user[<img src='https://cdn.iconscout.com/icon/free/png-512/free-development-2230922-1914286.png?f=webp&w=256' /> \nuser]
    
    subgraph frontend
    end

    user <-- requests --> frontend
    
    frontend <-- requests --> Service1
    frontend <-- requests --> Service2
    frontend <-- requests --> Service3

    subgraph backend
        Service1[<img src='https://cdn.iconscout.com/icon/premium/png-512-thumb/service-1407177-1190587.png?f=webp&w=256' /> \nService1]
        Service2[<img src='https://cdn.iconscout.com/icon/premium/png-512-thumb/service-1407177-1190587.png?f=webp&w=256' /> \nService2]
        Service3[<img src='https://cdn.iconscout.com/icon/premium/png-512-thumb/service-1407177-1190587.png?f=webp&w=256' /> \nService3]
        
        Service1 <-- call --> Service2
        Service1 <-- call --> Service3
        Service2 <-- call --> Service3
    end

    database[<img src='https://cdn.iconscout.com/icon/premium/png-512-thumb/database-1138-1150296.png?f=webp&w=256' /> \ndatabase]
    Service1 --> database
